// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface RevertingReceiver$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "RevertingReceiver";
  readonly sourceName: "contracts/test/RevertingReceiver.sol";
  readonly abi: [{"stateMutability":"payable","type":"receive"}];
  readonly bytecode: "0x6080604052348015600e575f5ffd5b5060ed8061001b5f395ff3fe6080604052366041576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401603890609b565b60405180910390fd5b5f5ffd5b5f82825260208201905092915050565b7f6e6174697665207472616e736665722072656a656374656400000000000000005f82015250565b5f60876018836045565b91506090826055565b602082019050919050565b5f6020820190508181035f83015260b081607d565b905091905056fea2646970667358221220c58a322dda21ec076d57f1cf0ec71146dfaeddbe86d84debf739abe40986dfc464736f6c634300081c0033";
  readonly deployedBytecode: "0x6080604052366041576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401603890609b565b60405180910390fd5b5f5ffd5b5f82825260208201905092915050565b7f6e6174697665207472616e736665722072656a656374656400000000000000005f82015250565b5f60876018836045565b91506090826055565b602082019050919050565b5f6020820190508181035f83015260b081607d565b905091905056fea2646970667358221220c58a322dda21ec076d57f1cf0ec71146dfaeddbe86d84debf739abe40986dfc464736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/test/RevertingReceiver.sol";
  readonly buildInfoId: "solc-0_8_28-b62306d27c5154ec81fd23364179566ffc8914dd";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["RevertingReceiver"]: RevertingReceiver$Type;
    ["contracts/test/RevertingReceiver.sol:RevertingReceiver"]: RevertingReceiver$Type;
  }
}